### ISSUE TITLE
Polybar Bar Doesn't Display Properly

### ISSUE THREAD

**Issue by vincula45** [ChrisTitusTech/Debian-titus#11]
The top polybar bar was displaying a black bar with white icons

If you look at the .Xresources, it refers to #include "/home/titus/.Xnord" on line 25.

I haven't played with using .Xresources in the past but maybe the reference should be:
#include "/home/$USER/.Xnord".

The polybar bar worked fine with the nord colors when using my username.

**Comment by petergr20** [comment]
bspwmrc:sudo /home/titus/GitHub/Debian-titus/dotfiles/bspwm/mount-drives.sh  here too

**Comment by ChrisTitusTech** [comment]
Looks like the script was putting the Xresources in the wrong spot. Should be fixed now.
