### ISSUE TITLE
unicode problem 

### ISSUE THREAD

**Issue by ExplosiveGreen** [ChrisTitusTech/Debian-titus#14]
in file dotfiles/rofi/powermenu/powermenu.sh
section Options
the Unicode don't show up and after using the powermenu show only the text E9C0 E9C4 E9A3 E991
also in section Confirmation and Message
after -theme reference a message and confirmation rofi file that doesn't exist in the location
also when you click on suspend or logout the lost click register as a click for getting out from the confirmation menu and with that you can answer that you Sure to the message
![Picture1](https://user-images.githubusercontent.com/69218745/145124997-5e5edccf-e001-4796-8ef7-52ad6f6ea7f0.png)
e

**Comment by feekApp** [comment]
Same here.

For me also some warnings in ~/.xsessions-errors like:
```
polybar|warn: Dropping unmatched character _ (U+f3ed) in '_ '
```

**Comment by ExplosiveGreen** [comment]
i fixed the unicode problem by downloadng this repository https://github.com/adi1090x/rofi.git 
and runing this two comands
mkdir -p "$HOME/.local/share/fonts"
cp -rf rofi/fonts/* "$HOME/.local/share/fonts"

**Comment by ExplosiveGreen** [comment]
for the message and confirm.rasi not found you can just change the URL for those files to .config/rofi/applets/styles/confirm.rasi
and  .config/rofi/applets/styles/message.rasi

and for the double clicking problem you can ether us your keyboard instead your mouse or put right before this line ans=$(confirm_exit &) a dummy menu

**Comment by aphive** [comment]
A bit late but, here is how I fixed mine... It's just the first few lines that need tweaking.

```
theme="$dir/powermenu/drop_square"
dir="$HOME/.config/rofi/"

confirm="$HOME/applets/styles/confirm.rasi"

rofi_command="rofi -theme $dir/$theme"

# Options
shutdown=""
reboot=""
lock=""
suspend=""
logout=""

# Confirmation
confirm_exit() {
	rofi -dmenu\
		-i\
		-no-fixed-num-lines\
		-p "Are You Sure? : "\
		-theme $confirm
}

# Message
msg() {
	rofi -theme "$confirm" -e "Available Options  -  yes / y / no / n"
}
```
