### ISSUE TITLE
polybar issues

### ISSUE THREAD

**Issue by SandupaTech** [ChrisTitusTech/Debian-titus#15]
1. polybar doesn't themed and it is black.
![2021-12-09_12-38_1](https://user-images.githubusercontent.com/93241017/145350698-238f423d-eac3-4f1c-87d5-5854a8a89672.png)

2. When title bar is long polybar doesn't display power menu.
![2021-12-09_12-40](https://user-images.githubusercontent.com/93241017/145350706-f7301581-d0ec-48bf-9ec7-94f8d2fcebb4.png)

**Comment by ExplosiveGreen** [comment]
for the theme problem go to ~/.Xresources to line 25 and change the include from
#include "/home/titus/.Xnord"
to 
#include "/home/your username/.Xnord"

and for the title problem go to ~/.config/polybar/config to line 289 and change the lable-maxlen to something smaller until it stop pushing the power menu button I put 58 but depending on the length of your display it could change

**Comment by SandupaTech** [comment]
> for the theme problem go to ~/.Xresources to line 25 and change the include from #include "/home/titus/.Xnord" to #include "/home/your username/.Xnord"

I did it but it doesn't work

> and for the title problem go to ~/.config/polybar/config to line 289 and change the lable-maxlen to something smaller until it stop pushing the power menu button I put 58 but depending on the length of your display it could change

I will try this

**Comment by SandupaTech** [comment]
@ExplosiveGreen Thank you for your comment.
2nd issue has solved now.
but still top bar is solid black, i have changed .Xresources line 25 to #include "/home/sandupa/.Xnord"
 but still same error


<h2> Here is the error message displayed while running through the terminal</h2>
> notice: Parsing config file: /home/sandupa/.config/polybar/config
error: Invalid value for "bar/bar.background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "bar/bar.foreground", using default value (reason: X resource "foreground" not found (no fallback set))
error: Invalid value for "bar/bar.line-color", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "bar/bar.border-color", using default value (reason: X resource "color0" not found (no fallback set))
error: Invalid value for "module/launcher.content-foreground", using default value (reason: X resource "color17" not found (no fallback set))
error: Invalid value for "module/launcher.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/sep.content-foreground", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/sep.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/left.content-foreground", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/left.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/left.content-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/left.content-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspwm.label-focused-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspwm.label-focused-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspwm.label-focused-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/bspwm.label-focused-foreground", using default value (reason: X resource "color4" not found (no fallback set))
error: Invalid value for "module/bspwm.label-occupied-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspwm.label-occupied-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspwm.label-occupied-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/bspwm.label-occupied-foreground", using default value (reason: X resource "color7" not found (no fallback set))
error: Invalid value for "module/bspwm.label-urgent-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspwm.label-urgent-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspwm.label-urgent-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/bspwm.label-urgent-foreground", using default value (reason: X resource "color1" not found (no fallback set))
error: Invalid value for "module/bspwm.label-empty-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspwm.label-empty-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspwm.label-empty-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/bspwm.label-empty-foreground", using default value (reason: X resource "color0" not found (no fallback set))
error: Invalid value for "module/bspwm.label-separator-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspwm.label-separator-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspwm.label-separator-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/right.content-foreground", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/right.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/right.content-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/right.content-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/sep.content-foreground", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/sep.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/left.content-foreground", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/left.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/left.content-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/left.content-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bsplayout.format-foreground", using default value (reason: X resource "color1" not found (no fallback set))
error: Invalid value for "module/bsplayout.format-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/bsplayout.label-monocle-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bsplayout.label-monocle-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bsplayout.label-tiled-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bsplayout.label-tiled-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspmode.format-foreground", using default value (reason: X resource "color1" not found (no fallback set))
error: Invalid value for "module/bspmode.format-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/bspmode.label-fullscreen-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspmode.label-fullscreen-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspmode.label-floating-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspmode.label-floating-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspmode.label-pseudotiled-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspmode.label-pseudotiled-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspmode.label-locked-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspmode.label-locked-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspmode.label-sticky-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspmode.label-sticky-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspmode.label-private-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspmode.label-marked-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/bspmode.label-marked-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/right.content-foreground", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/right.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/right.content-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/right.content-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/xwindow.format-foreground", using default value (reason: X resource "color14" not found (no fallback set))
error: Invalid value for "module/xwindow.format-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/xwindow.format-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/xwindow.format-prefix-foreground", using default value (reason: X resource "color14" not found (no fallback set))
error: Invalid value for "module/left.content-foreground", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/left.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/left.content-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/left.content-overline", using default value (reason: X resource "background" not found (no fallback set))
notice: pulseaudio: using default sink alsa_output.pci-0000_00_1b.0.analog-stereo
error: Invalid value for "module/pulseaudio.format-volume-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/pulseaudio.format-volume-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/pulseaudio.format-volume-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/pulseaudio.format-muted-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/pulseaudio.format-muted-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/pulseaudio.label-volume-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/pulseaudio.label-volume-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/pulseaudio.label-volume-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/pulseaudio.label-volume-foreground", using default value (reason: X resource "color6" not found (no fallback set))
error: Invalid value for "module/pulseaudio.label-muted-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/pulseaudio.label-muted-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/pulseaudio.label-muted-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/pulseaudio.label-muted-foreground", using default value (reason: X resource "color6" not found (no fallback set))
error: Invalid value for "module/pulseaudio.ramp-volume-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/pulseaudio.ramp-volume-foreground", using default value (reason: X resource "color6" not found (no fallback set))
error: Invalid value for "module/right.content-foreground", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/right.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/right.content-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/right.content-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/sep.content-foreground", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/sep.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/left.content-foreground", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/left.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/left.content-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/left.content-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Disabling module "bluetooth" (reason: Missing section "module/bluetooth")
error: Invalid value for "module/vpn.format-foreground", using default value (reason: X resource "color5" not found (no fallback set))
error: Invalid value for "module/vpn.format-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/vpn.format-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/vpn.format-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Disabling module "pomod" (reason: Missing section "module/pomod")
error: Invalid value for "module/dunst.format-foreground", using default value (reason: X resource "color3" not found (no fallback set))
error: Invalid value for "module/dunst.format-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/dunst.format-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/dunst.format-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/redshift.format-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/redshift.format-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/redshift.format-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/right.content-foreground", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/right.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/right.content-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/right.content-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/sep.content-foreground", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/sep.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/left.content-foreground", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/left.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/left.content-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/left.content-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/eth.format-connected-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/eth.format-connected-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/eth.format-connected-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/eth.format-connected-prefix-foreground", using default value (reason: X resource "color5" not found (no fallback set))
error: Invalid value for "module/eth.format-disconnected-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/eth.format-disconnected-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/eth.label-connected-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/eth.label-connected-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/wlan.format-connected-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/wlan.format-connected-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/wlan.format-connected-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/wlan.format-disconnected-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/wlan.format-disconnected-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/wlan.format-disconnected-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/wlan.ramp-signal-foreground", using default value (reason: X resource "color5" not found (no fallback set))
error: Invalid value for "module/wlan.label-connected-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/wlan.label-connected-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/wlan.label-connected-foreground", using default value (reason: X resource "color5" not found (no fallback set))
error: Invalid value for "module/wlan.label-disconnected-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/wlan.label-disconnected-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Disabling module "wlan" (reason: Invalid network interface "wlp3s0")
error: Invalid value for "module/right.content-foreground", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/right.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/right.content-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/right.content-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/sep.content-foreground", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/sep.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/left.content-foreground", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/left.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/left.content-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/left.content-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/time.format-foreground", using default value (reason: X resource "color2" not found (no fallback set))
error: Invalid value for "module/time.format-background", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/time.format-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/time.format-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/time.format-prefix-foreground", using default value (reason: X resource "color2" not found (no fallback set))
error: Invalid value for "module/right.content-foreground", using default value (reason: X resource "color16" not found (no fallback set))
error: Invalid value for "module/right.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/right.content-underline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/right.content-overline", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/sep.content-foreground", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/sep.content-background", using default value (reason: X resource "background" not found (no fallback set))
error: Invalid value for "module/powermenu.content-foreground", using default value (reason: X resource "color17" not found (no fallback set))
error: Invalid value for "module/powermenu.content-background", using defa

**Comment by SandupaTech** [comment]
> xrdb ~/.Xresources
> xrdb -merge ~/.Xresources

These two commands solved my issue.
