### ISSUE TITLE
variety - script - set-wallpaper returning an error

### ISSUE THREAD

**Issue by mertensj** [ChrisTitusTech/Debian-titus#25]
variety / scripts / set_wallpaper 
for simple WM is depending on feh or nitrogen 
both are missing , so it fails

possible solution: add package feh in user.sh script ?

sudo apt install feh

**Comment by ynsnf** [comment]
Yes, That would resolve it

**Comment by Meyu-Sys** [comment]
#47 added feh to root.sh and added wallpaper to Pictures directory wallpaper is hardcoded at bspwmrc
