### ISSUE TITLE
The Screen is flashing it self

### ISSUE THREAD

**Issue by blusewilll** [ChrisTitusTech/Debian-titus#28]
I don't know only I have this problem or not but my screen is flashing sometimes and it's more regularly when you run osu!lazer (I know I am not supposed to run games but it's happen sometimes not even in game) I don't know it's the graphics card driver issue or not (I am using NVIDIA GeForce GTX 750 Ti ) Hope someone can fixed my issue.

**Comment by nikkuuwux** [comment]
Ill download lazer to see if I can replicate. To be honest, osu is very important to me and if it was not working for some reason, I would be motivated enough to debug and troubleshoot until my eyeballs fell out. 
Just saying its nice to have a osu homie here and I got your back.

Have you happened to try using aptitude to see if there are any missing or broken dependencies? Also, maybe it could be driver related? Let me know what you see with aptitude and ime sure something can be configured.

**Comment by nikkuuwux** [comment]
It is probably because osu is running at 10000fps... and almost absolutely 0 latency.
I reccomend setting the in game frame limit to low power or optimal. 

If you want to try editing the config file for osu then try keeping the FPS withibin a multiple of your monitors refresh rate. So if 60hz monitor then try setting framecap at 60, 120, 180, 240, etc

**Comment by blusewilll** [comment]
I mean it's like this even I am not running osu lazer the screen seems like flash to the desktop background it self
[Video](https://www.youtube.com/watch?v=tuwV5WbLQ74)

**Comment by nielsdrost7** [comment]
Doesn't this has something to do with vsync?
Did you install Chris's repo in a virtual PC (KVM) or on hardware?

**Comment by blusewilll** [comment]
No this is on real hardware not KVM virtual machine

**Comment by nielsdrost7** [comment]
I can't reproduce at the moment, cuz I'll be in VM's for a while. I still think you should look into turning off vsync.
In Chris's video... at the beginning... he turns off vsync as well (he was in a VM though)

The flashing... it's not the same as the 'screen tearing', that's happening in KDE, correct?

@ChrisTitusTech right before you switched graphics cards, you had an Nvidia in your box, correct?
You did something to the X11.conf (you said in 1 of your videos, but you didn't show what you had in there)

Can you tell us poor Nvdia users what it was?

**Comment by blusewilll** [comment]
No turn off Vsync makes it flash more often so also not works
I think we need to wait @ChrisTitusTech to answer my question now.

**Comment by ChrisTitusTech** [comment]
I'd make sure you force composition pipeline in `nvidia-xconfig`
![Titus Reacts to Linus Tech Tips Linux Daily Drive Challenge 18-1 screenshot](https://user-images.githubusercontent.com/7896101/147855862-72606fd5-d35b-4cc6-8886-a8c89d276ab3.png)

**Comment by blusewilll** [comment]
Problem Solved Thanks : D
