### ISSUE TITLE
Why not just download the sid ISO instead?

### ISSUE THREAD

**Issue by aphive** [ChrisTitusTech/Debian-titus#29]
Not an issue but a suggestion...

The current OS setup forces you into having to update sources and all the extra steps that come with it when you can just install the testing OS `firmware-testing-amd64-i386-netinst.iso` from the get go.

https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/daily-builds/sid_d-i/current/multi-arch/iso-cd/

Also, it should be noted that anything other than Bullseye (stable) does not get security updates in a timely manner for those that are / would be concerned about that..

> Please note that security updates for "unstable" distribution are not managed by the security team. Hence, "unstable" does not get security updates in a timely manner.

> Please note that security updates for "testing" distribution are not yet managed by the security team. Hence, "testing" does not get security updates in a timely manner. 

> You are encouraged to switch your sources.list entries from testing to bullseye for the time being if you need security support.

**Comment by aphive** [comment]
Oh, just noticed that is only i386.

**Comment by ChrisTitusTech** [comment]
Yeah the amd64 daily builds don't seem to be updated and why I moved to testing iso.
