### ISSUE TITLE
Matching sddm theme

### ISSUE THREAD

**Issue by aphive** [ChrisTitusTech/Debian-titus#31]
Not sure how this could be added to the install but this would be great to have as part of it all.
https://store.kde.org/p/1590039

**Comment by aphive** [comment]
I'm working on a matching theme for the sddm login window, will be adding here:

**Comment by aphive** [comment]
Made the first full push. Let me know.

**Comment by Meyu-Sys** [comment]
Hey  I have already made a pull request for sddm theming (see #41 ) you can change it to your liking by changing the tar archive in the root of the directory from there you just have to change the command in root.sh to match your tar archive

**Comment by aphive** [comment]
Nice, I just wanted to have something to learn with :)

**Comment by Meyu-Sys** [comment]
it is not finished if you have used sddm before you could do it but i am yet to make a config

**Comment by Meyu-Sys** [comment]
this can be closed sddm theming is added

**Comment by ChrisTitusTech** [comment]
Added PR #41
