### ISSUE TITLE
Window Icons not showing up

### ISSUE THREAD

**Issue by Jacks123459** [ChrisTitusTech/Debian-titus#32]
The icons for the different windows such as browser, terminal aren't showing up/

**Comment by aphive** [comment]
Same here, just did a fresh install. Several things don't seem to work like the volume icon does nothing when interacted with. For the icons section all I see is a gray circle. Trying to play with settings at the moment to see if I can figure this out
![PXL_20211231_035212414](https://user-images.githubusercontent.com/6079962/147802340-5ba7d50c-4f1d-435d-be30-802605fcfbe6.jpg)
.

**Comment by nielsdrost7** [comment]
It's the icons for all the available desktops, that aren't showing up. Could you check the bspwm config file?
Maybe add 1 desktop at a time and then see if it will show up?
You might need to refresh bspwm after adding a desktop with its icon.

**Comment by Jacks123459** [comment]
I was configuring it for 3 hours, no luck

**Comment by nielsdrost7** [comment]
Go to ~/.config/bspwm/bspwmrc

**Comment by ChrisTitusTech** [comment]
This was my fault. I have now fixed this.
