### ISSUE TITLE
Feature Request: Use doas instead of sudo

### ISSUE THREAD

**Issue by WitherCubes** [ChrisTitusTech/Debian-titus#6]
As this is aimed for advanced users and minimal, why not use doas as an alternative to sudo.

https://wiki.debian.org/Doas

**Comment by Eroldin** [comment]
Might be an idea, we need to repackage the AUR's opendoas-sudo package, as there are packages which depend on sudo

**Comment by WitherCubes** [comment]
opendoas-sudo just symlinks sudo to doas. So I think there is no need to make a package for it.

`ln -s $(which doas) "$pkgdir"/usr/bin/sudo`

**Comment by Eroldin** [comment]
Keep in mind the some programs depend on the sudo package. making a opendoas-sudo package prevents dependency issius.
