### ISSUE TITLE
Power management and touchpad issues.

### ISSUE THREAD

**Issue by t4technow** [ChrisTitusTech/Debian-titus#63]
I installed this setup on a laptop and It had many issues but the main one is the brightness problem. As there is no way to adjust it manually I tried increasing it with "xrandr" from the terminal and set it max. But it still feels pretty dim when compared to the manjaro that is dual booted on the same system. Oh and what is the 11%  button it seems like brightness control but can't make it work. The other issue I'm facing is that the touch pad tap to click functionality won't work properly, I have to switch it off and then switch it back on every single time I restart my system.

**Comment by MYBLtd** [comment]
Just installed it on a laptop and love it. Also here no power management. I get an error: "The Power Management Service appears not to be running" . A lot of of hits on this in search engines but until I couldn't solve this. Upower is running fine, i have a feeling it is a dbus problem. Laptop is a gaming one and running on full power :-(

**Comment by t4technow** [comment]
Thanks for the support man. But unfortunately `Executing: /usr/lib/x86_64-linux-gnu/libexec/org_kde_powerdevil` didn't work for me. It trowed a bunch of errors such as "org.kde.powerdevil: org.kde.powerdevil.chargethresholdhelper.getthreshold failed .... " and "org.kde.powerdevil: Handle button events action could not check for screen configuration".

**Solved Touchpad issue**
I had to add Option `"Tapping" "True"` to the entry `MatchIsTouchpad` in the file `/usr/share/X11/xorg.conf.d/40-libinput.conf`.

_It will be like this:_
```
Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        Option "Tapping" "True"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
EndSection
```

Ooh and I too love this setup.
