### ISSUE TITLE
Several Questions

### ISSUE THREAD

**Issue by ryu-tux** [ChrisTitusTech/Debian-titus#74]
I just started using this WM, I'm still a newbie on Window Managers so I got several questions on mine when using this one.

1. I only use laptop for this so I don't know how do I fix the screen tearing issue, especially when browsing it really screen tears a lot.
2. The window titles on the polybar sometimes overlaps when the tab has usually long phrase so I'm not also sure how do I get to fix it.

So far I have a good experience on this, really good alternative and I have adopted already the usage of the keyboards, Hopefully someone will answer, thank you!

**Comment by nxjosephofficial** [comment]
Hi. I don't know about screen tearing but you can set title length in polybar.

```
file: ~/.config/polybar/config.ini

[module/xwindow]
type = internal/xwindow
label = %title%
label-maxlen = 60
label-empty = Desktop 
```
Here, you can adjust the `label-maxlen` value.
