### ISSUE TITLE
Link broken on introduction docs

### ISSUE THREAD

**Issue by anthonybouton** [ChrisTitusTech/Debian-titus#79]
Hi Chris,

Fan of your youtube page and this github repo.
Just wanted to mention that the link to download the ISO is broken, mostly because of the change debian mentioned here
https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/

Since I'm still learning how all of Linux works, I've went with the following alternative.
If I knew a little bit more about Linux/Debian, I've would've update it myself and sent you a PR to merge it into the main branch.
https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/current/amd64/iso-cd/

Just wanted to let you know, keep up the good work! <3

**Comment by bckelley** [comment]
27-Feb still broken

**Comment by alexsch01** [comment]
I made a pull request to correct the link to the updated one: https://github.com/ChrisTitusTech/Debian-titus/pull/80

@anthonybouton what you want is this URL: https://cdimage.debian.org/cdimage/weekly-builds/amd64/iso-cd/
