### ISSUE TITLE
Weird terminal After Installing Debian Titus

### ISSUE THREAD

**Issue by TechTune-1** [ChrisTitusTech/Debian-titus#99]
Hello,
I just installed Debian-Titus bspwm branch. However, 
when I rebooted my PC, the starting screen was stuck when it said that sddm was starting, so I pressed Alt+F2 to access the terminal, but the terminal was displaying weirdly and there wasn’t any login screen or WM. I'm not sure how to fix it. Any advice is appreciated.
![2469A4F3-A224-447B-A823-3568CA6FF06A](https://github.com/ChrisTitusTech/Debian-titus/assets/87855669/8e42214a-b54b-4db7-bca5-c5138271e4d3)

**Comment by markupstart** [comment]
Not sure the process you took.  I installed a fresh copy of debian from the link listed and followed the instructions on the bspwn branch page and it installed as expected.  I rebooted and logged into the bspwn window manager.  Everything seems to be in working order, no messages or errors reported.

**Comment by TechTune-1** [comment]
Hello @markupstart, I followed your instructions to install Debian-Titus, but it did not work for me. I have attached a sped up video of the steps I took. Could you please watch it and give me some guidance? Thank you for your help.

**Comment by markupstart** [comment]
@TechTune-1 What kind of video card you got on your system?  Intel, AMD, or Nvidia?
It looked based off the video that at the end sddm loaded, but never showed the graphical login? Then you dropped to the tty to see if that was the case.

**Comment by markupstart** [comment]
I got the same issue on reboot with real hardware. It's a typical nvidia thing.  Seen this lots.  When it boots to the boot menu hit e to edit.  At the end of the linux line type in nomodeset and hit F10 to boot. Once you install the nvidia drivers it will be good to go...if of course you do have an nvidia card.

**Comment by TechTune-1** [comment]
> I got the same issue on reboot with real hardware. It's a typical nvidia thing. Seen this lots. When it boots to the boot menu hit e to edit. At the end of the linux line type in nomodeset and hit F10 to boot. Once you install the nvidia drivers it will be good to go...if of course you do have an nvidia card.

I’ve got an AMD Radeon RX 6600 Graphics Card, so I don’t think this solution will work for me. Do you have any other ideas on how to fix this problem? I really appreciate your help.

**Comment by markupstart** [comment]
No idea then. For some reason sddm was not working as expected as it should have booted you to the graphical login screen.

**Comment by markupstart** [comment]
You can try to restart sddm to see if that brings up the login screen. If it does might be able to figure out why. Also maybe check the error log for xorg to see if anything is there.

**Comment by markupstart** [comment]
I've done a little more research. nomodeset could work even with amd cards. I would try that first to see if it gets you to the graphical login screen.

**Comment by TechTune-1** [comment]
Using nomodeset did indeed bring me to the login screen. After installing the AMD graphics drivers and configuring the desktop, everything works as expected. Thank you for helping me solve the issue. I appreciate your assistance a lot!
